apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- namespace.yaml

namespace: cloud-alphavantage
#nameSuffix: -prod

commonLabels:
  arch: x86

patchesStrategicMerge:
- deployment_replicas.yaml
- deployment_env.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
  - name: app-config
    literals:
      - SYMBOL=IBM
      - NDAYS=10

secretGenerator:
  - name: credentials
    type: Opaque
    literals:
      - APIKEY=RABZYXWVHB8MX5GO

#patchesJson6902:
#- target:
#    namespace: alphavantage
#    group: io.k8s.api.core
#    version: v1
#    kind: Service
#    name: service.yaml
#  path: ports.yaml