apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphavantage
spec:
  template:
    spec:
      containers:
        - name: alphavantage
          image: badmullafo/alphavantage:1.0_arm
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: foo
              value: we-are-in-prod
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: credentials
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 10
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 10